/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.9.2                                               */
/*  Date (dd.mm.yyyy): 20.12.2021   Time (hh:mm): 14:32                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_32ARGB
#define DISPLAY_1_X_RESOLUTION 480
#define DISPLAY_1_Y_RESOLUTION 272
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_ADC 5
#define GX_PIXELMAP_ID_BK 6
#define GX_PIXELMAP_ID_CAMERA 7
#define GX_PIXELMAP_ID_CAN 8
#define GX_PIXELMAP_ID_CLOCK 9
#define GX_PIXELMAP_ID_COMPUTER 10
#define GX_PIXELMAP_ID_DAC 11
#define GX_PIXELMAP_ID_FM 12
#define GX_PIXELMAP_ID_GPRS 13
#define GX_PIXELMAP_ID_GPS 14
#define GX_PIXELMAP_ID_MPU 15
#define GX_PIXELMAP_ID_MUSIC 16
#define GX_PIXELMAP_ID_NET 17
#define GX_PIXELMAP_ID_PIC 18
#define GX_PIXELMAP_ID_READER 19
#define GX_PIXELMAP_ID_RECORDER 20
#define GX_PIXELMAP_ID_SYSTEM 21
#define GX_PIXELMAP_ID_USB 22
#define GX_PIXELMAP_ID_VIDEO 23
#define GX_PIXELMAP_ID_WIFI 24
#define GX_PIXELMAP_ID_WIRELESS 25
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 26

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define DISPLAY_1_STRING_TABLE_SIZE 13

#endif                                       /* sentry                         */
